# Generated by Django 6.0.4 on 2026-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Insert Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
