# Generated by Django 6.0.4 on 2026-05-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('catagory', '0003_remove_catagory_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catagory.catagory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_cover'),
        ),
    ]
