# Generated by Django 6.0.4 on 2026-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.IntegerField(help_text='catagory id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='catagory name', max_length=100, verbose_name='Catagory  Name')),
            ],
        ),
    ]
