# Generated by Django 6.0.4 on 2026-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
