# Generated by Django 6.0.4 on 2026-05-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_catagory_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='test',
        ),
    ]
